<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>3fc40fd1-5b5f-4432-a851-2198b0825ae2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PetSpace.Core\PetSpace.Core.csproj" />
    <ProjectReference Include="..\PetSpace.Data\PetSpace.Data.csproj" />
  </ItemGroup>

</Project>
