<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PetSpace.Core\PetSpace.Core.csproj" />
    <ProjectReference Include="..\PetSpace.Data\PetSpace.Data.csproj" />
  </ItemGroup>

</Project>
